trigger:
 - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile.dev
